"""Modify Report model columns: ms timestamps, remove owner

Revision ID: 01519e8a80f9
Revises: 132eec3de389
Create Date: 2025-04-12 14:14:32.818100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01519e8a80f9'
down_revision: Union[str, None] = '132eec3de389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('start_time_ms', sa.BigInteger(), nullable=False))
    op.add_column('reports', sa.Column('end_time_ms', sa.BigInteger(), nullable=False))
    op.drop_column('reports', 'start_time')
    op.drop_column('reports', 'end_time')
    op.drop_column('reports', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('owner', sa.VARCHAR(), nullable=True))
    op.add_column('reports', sa.Column('end_time', sa.DATETIME(), nullable=True))
    op.add_column('reports', sa.Column('start_time', sa.DATETIME(), nullable=True))
    op.drop_column('reports', 'end_time_ms')
    op.drop_column('reports', 'start_time_ms')
    # ### end Alembic commands ###
