"""Initial migration with all tables

Revision ID: 132eec3de389
Revises: 
Create Date: 2025-04-12 14:04:36.911862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132eec3de389'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('zone_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_code'), 'reports', ['report_code'], unique=True)
    op.create_table('fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('wcl_fight_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('boss_id', sa.Integer(), nullable=True),
    sa.Column('start_time_offset', sa.Integer(), nullable=False),
    sa.Column('end_time_offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fights_id'), 'fights', ['id'], unique=False)
    op.create_index(op.f('ix_fights_wcl_fight_id'), 'fights', ['wcl_fight_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('wcl_actor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('server', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'wcl_actor_id', name='uq_player_report_actor')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_wcl_actor_id'), 'players', ['wcl_actor_id'], unique=False)
    op.create_table('buff_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('ability_game_id', sa.Integer(), nullable=False),
    sa.Column('source_player_id', sa.Integer(), nullable=True),
    sa.Column('target_player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['source_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['target_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buff_events_ability_game_id'), 'buff_events', ['ability_game_id'], unique=False)
    op.create_index(op.f('ix_buff_events_event_type'), 'buff_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_buff_events_fight_id'), 'buff_events', ['fight_id'], unique=False)
    op.create_index(op.f('ix_buff_events_id'), 'buff_events', ['id'], unique=False)
    op.create_index(op.f('ix_buff_events_source_player_id'), 'buff_events', ['source_player_id'], unique=False)
    op.create_index(op.f('ix_buff_events_target_player_id'), 'buff_events', ['target_player_id'], unique=False)
    op.create_index(op.f('ix_buff_events_timestamp_ms'), 'buff_events', ['timestamp_ms'], unique=False)
    op.create_table('player_cast_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('ability_game_id', sa.Integer(), nullable=False),
    sa.Column('source_player_id', sa.Integer(), nullable=False),
    sa.Column('target_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['source_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['target_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_cast_events_ability_game_id'), 'player_cast_events', ['ability_game_id'], unique=False)
    op.create_index(op.f('ix_player_cast_events_fight_id'), 'player_cast_events', ['fight_id'], unique=False)
    op.create_index(op.f('ix_player_cast_events_id'), 'player_cast_events', ['id'], unique=False)
    op.create_index(op.f('ix_player_cast_events_source_player_id'), 'player_cast_events', ['source_player_id'], unique=False)
    op.create_index(op.f('ix_player_cast_events_target_player_id'), 'player_cast_events', ['target_player_id'], unique=False)
    op.create_index(op.f('ix_player_cast_events_timestamp_ms'), 'player_cast_events', ['timestamp_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_cast_events_timestamp_ms'), table_name='player_cast_events')
    op.drop_index(op.f('ix_player_cast_events_target_player_id'), table_name='player_cast_events')
    op.drop_index(op.f('ix_player_cast_events_source_player_id'), table_name='player_cast_events')
    op.drop_index(op.f('ix_player_cast_events_id'), table_name='player_cast_events')
    op.drop_index(op.f('ix_player_cast_events_fight_id'), table_name='player_cast_events')
    op.drop_index(op.f('ix_player_cast_events_ability_game_id'), table_name='player_cast_events')
    op.drop_table('player_cast_events')
    op.drop_index(op.f('ix_buff_events_timestamp_ms'), table_name='buff_events')
    op.drop_index(op.f('ix_buff_events_target_player_id'), table_name='buff_events')
    op.drop_index(op.f('ix_buff_events_source_player_id'), table_name='buff_events')
    op.drop_index(op.f('ix_buff_events_id'), table_name='buff_events')
    op.drop_index(op.f('ix_buff_events_fight_id'), table_name='buff_events')
    op.drop_index(op.f('ix_buff_events_event_type'), table_name='buff_events')
    op.drop_index(op.f('ix_buff_events_ability_game_id'), table_name='buff_events')
    op.drop_table('buff_events')
    op.drop_index(op.f('ix_players_wcl_actor_id'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_fights_wcl_fight_id'), table_name='fights')
    op.drop_index(op.f('ix_fights_id'), table_name='fights')
    op.drop_table('fights')
    op.drop_index(op.f('ix_reports_report_code'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
