"""Modify Fight model columns to match schema

Revision ID: 30af627fa7df
Revises: 01519e8a80f9
Create Date: 2025-04-12 14:18:47.030725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30af627fa7df'
down_revision: Union[str, None] = '01519e8a80f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fights', sa.Column('start_time_ms', sa.BigInteger(), nullable=True))
    op.add_column('fights', sa.Column('end_time_ms', sa.BigInteger(), nullable=True))
    op.add_column('fights', sa.Column('start_offset_ms', sa.BigInteger(), nullable=False))
    op.add_column('fights', sa.Column('end_offset_ms', sa.BigInteger(), nullable=False))
    op.add_column('fights', sa.Column('kill', sa.Boolean(), nullable=True))
    op.add_column('fights', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('fights', sa.Column('boss_percentage', sa.Float(), nullable=True))
    op.add_column('fights', sa.Column('average_item_level', sa.Float(), nullable=True))
    op.drop_column('fights', 'start_time_offset')
    op.drop_column('fights', 'boss_id')
    op.drop_column('fights', 'end_time_offset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fights', sa.Column('end_time_offset', sa.INTEGER(), nullable=False))
    op.add_column('fights', sa.Column('boss_id', sa.INTEGER(), nullable=True))
    op.add_column('fights', sa.Column('start_time_offset', sa.INTEGER(), nullable=False))
    op.drop_column('fights', 'average_item_level')
    op.drop_column('fights', 'boss_percentage')
    op.drop_column('fights', 'difficulty')
    op.drop_column('fights', 'kill')
    op.drop_column('fights', 'end_offset_ms')
    op.drop_column('fights', 'start_offset_ms')
    op.drop_column('fights', 'end_time_ms')
    op.drop_column('fights', 'start_time_ms')
    # ### end Alembic commands ###
